server:
  port: 5000
spring:
  application:
    name: gateway
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: usersModule
          uri: lb://user
          predicates:
            - Path=/users/**
        - id: postMoule
          uri: lb://post
          predicates:
            - Path=/posts/**
        - id: vendorModule
          uri: lb://vendor
          predicates:
            - Path=/vendors/**
logging:
  level:
    web: debug
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}
