server:
  port: 5000
spring:
  application:
    name: gateway
  profiles:
    active: home
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: authModule
          uri: lb://auth
          predicates:
            - Path=/auths/**
        - id: postModule
          uri: lb://post
          predicates:
            - Path=/posts/**
        - id: vendorModule
          uri: lb://vendor
          predicates:
            - Path=/vendors/**
  loadbalancer:
    ribbon:
      enabled: false
logging:
  level:
    web: info

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka