spring:
  cloud:
    consul:
      host: localhost
      port: 5500
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${server.port}

# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus, health
  # For Exemplars to work we need histogram buckets
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logging:
  level:
    web: info
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"